### ISSUE TITLE
What is the a variant version of BEiTv2 used in ViT-Adapter?

### ISSUE THREAD

**Issue by HITerStudy** [Traffic-X/ViT-CoMer#1]
As describled in the paper(Table 4. Comparisons with previous SOTA on COCO val 2017), the pretrain checkpoint from the a variant version of BEiTv2 used in ViT-Adapter can improve the performance, please give some details, thanks!

**Comment by Jeremy-lf** [comment]
> As describled in the paper(Table 4. Comparisons with previous SOTA on COCO val 2017), the pretrain checkpoint from the a variant version of BEiTv2 used in ViT-Adapter can improve the performance, please give some details, thanks!

The original intention of ViT-CoMer is that it can directly utilize open-source ViT pre-training instead of retraining large-scale pre-training. Therefore, we combined BEiTv2 with other advanced pre-training and also used TTA during testing, both of which improved the performance of the model.
