### ISSUE TITLE
请问Beit2*和Beit2有什么区别呢

### ISSUE THREAD

**Issue by dhddxdhd** [Traffic-X/ViT-CoMer#16]
困惑

**Comment by Jeremy-lf** [comment]
We have enhanced the pre-training of BEiT2 by combining it with other open-source pre training, which is one of the advantages of ViT-CoMer.

**Comment by dhddxdhd** [comment]
> 我们通过将 BEiT2 与其他开源预训练相结合来增强 BEiT2 的预训练，这是 ViT-CoMer 的优势之一。[#1 （评论）](https://github.com/Traffic-X/ViT-CoMer/issues/1#issuecomment-2011327087)

请问对应的预训练模型或者训练好的co_detr模型能开源不

**Comment by Jeremy-lf** [comment]
> > 我们通过将 BEiT2 与其他开源预训练相结合来增强 BEiT2 的预训练，这是 ViT-CoMer 的优势之一。[#1 （评论）](https://github.com/Traffic-X/ViT-CoMer/issues/1#issuecomment-2011327087)
> 
> 请问对应的预训练模型或者训练好的co_detr模型能开源不

We will release it in the future

**Comment by dhddxdhd** [comment]
> > > 我们通过将 BEiT2 与其他开源预训练相结合来增强 BEiT2 的预训练，这是 ViT-CoMer 的优势之一。[#1 （评论）](https://github.com/Traffic-X/ViT-CoMer/issues/1#issuecomment-2011327087)
> > 
> > 
> > 请问对应的预训练模型或者训练好的co_detr模型能开源不
> 
> We will release it in the future

我没有问题了，非常期待您发布这些模型权重
