### ISSUE TITLE
数据维度不匹配

### ISSUE THREAD

**Issue by shellxiao** [Traffic-X/ViT-CoMer#17]
跑自己的数据集，img_scale 和 crop_size 都是 112 x 112，运行程序报错：
    x = self.dwconv(x, H, W)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/xiaoxu/Segmentation/ViT-CoMer/segmentation/mmseg_custom/models/backbones/comer_modules.py", line 155, in forward 
x1 = x[:, 0:16 * n, :].transpose(1, 2).view(B, C, H * 2, W * 2).contiguous()
RuntimeError: shape '[2, 1152, 14, 14]' is invalid for input of size 442368

**Comment by GuoSicen** [comment]
我也遇到了同样的问题，请问你是怎么解决的呢

**Comment by shellxiao** [comment]
> 我也遇到了同样的问题，请问你是怎么解决的呢
暂时没有解决

**Comment by fyting** [comment]
@shellxiao Both the height (h) and width (w) of the crop_size (or image_size) need to be divisible by 32.

**Comment by Whu-rs-lcx** [comment]
我也遇到了同样的问题，而且我的image_size是256，可以被32整除
