### ISSUE TITLE
Question about the process of ViT-Comer

### ISSUE THREAD

**Issue by ShirleySyh** [Traffic-X/ViT-CoMer#18]
Thank you for your excellent work. I have a small question here. In the forward function of class ViTCoMer in vit_comer.py, there is a deform operation on input features. Why do we need this operation before patch embedding? Could you explain this operation in more detail? Thank you!

**Comment by Jeremy-lf** [comment]
@ShirleySyh It will be used in MSDeformAttention modules, more details are as follows:
https://github.com/Traffic-X/ViT-CoMer/blob/1dd3ada6e3568626c5b17a3fbb732dd8c06a39f3/detection/mmdet_custom/models/backbones/comer_modules.py#L188

**Comment by ShirleySyh** [comment]
Thank you for your reply. I have another question. In your paper in Section 3.3, features from ViTs are added to the F<sub>4</sub> to get F<sup>'</sup><sub>4</sub> and then F<sub>3</sub>, F<sup>'</sup><sub>4</sub>, F<sub>5</sub> are unified through Multi-Scale Deformable-Attention. However, in **class CTI_toV** in **Line 351** [https://github.com/Traffic-X/ViT-CoMer/blob/main/detection/mmdet_custom/models/backbones/comer_modules.py](url), it seems that features from ViTs are added to the multi-scale features after the multi-scale faetures pass through the Multi-Scale Deformable-Attention. Features from ViTs are not unified with multi-scale CNN features, which is different from the discription in paper. I'm not sure if it's my misunderstanding of the code or paper. Looking forward to your answer. Thank you!
