### ISSUE TITLE
adapting to patch_size 14

### ISSUE THREAD

**Issue by Guptajakala** [Traffic-X/ViT-CoMer#19]
Hi, thanks for your great work! I wanted to adapt this work to DINO which uses patch_size 14, while the current one assumes the ViT backbone with patch size 16. Do you have any suggestion about what's the best way to handle this?

**Comment by Jeremy-lf** [comment]
> Hi, thanks for your great work! I wanted to adapt this work to DINO which uses patch_size 14, while the current one assumes the ViT backbone with patch size 16. Do you have any suggestion about what's the best way to handle this?

you only need to resize patch embeding weights 14x14 to 16x16.
