### ISSUE TITLE
花架子搞的飞起

### ISSUE THREAD

**Issue by LMWL-HL** [Traffic-X/ViT-CoMer#21]
既然开源能不能稍微用心点，一运行起来各种问题。
脚本里参数--local-rank写成--local_rank。开源之前都没测试过吗。
还有'pretrained/dinov2_vitb14_pretrain_14to16_torch17.pth'这个文件在哪呀，能说明一下吗？
文档里的环境安装都老掉牙了，没试过能不能运行吗。开源不是针对你们公司里的老机器开源。

**Comment by Waiting4Wind** [comment]
Good call ！！！！
The environment deployment in this article is a piece of shit！！！！！！！
