### ISSUE TITLE
How does VIT-CoMer perform on the classification task?

### ISSUE THREAD

**Issue by luckydog11** [Traffic-X/ViT-CoMer#3]
Please, do you try to  run experiments on Imagenet datasets?

**Comment by clxia12** [comment]
Yes, we validated the classification performance of ViT-CoMer on ImageNet-1K, and the results are as follows:
<img width="325" alt="cls" src="https://github.com/Traffic-X/ViT-CoMer/assets/34881413/3df9e353-5155-4d2a-9129-70617bcbf7fe">

**Comment by JihwanEom** [comment]
@clxia12 Hello, how did you used the multiscale features for classification task? Current backbone returns list of tensors with multiple shapes.
```bash
        # Final Norm
        f1 = self.norm1(c1)
        f2 = self.norm2(c2)
        f3 = self.norm3(c3)
        f4 = self.norm4(c4)
        return [f1, f2, f3, f4]
```
