### ISSUE TITLE
checkpoint of backbone

### ISSUE THREAD

**Issue by greenhorn990628** [Traffic-X/ViT-CoMer#5]
Thanks for the nice work and congratulations for your being accepted by CVPR 2024. I found the checkpoint file of backbone in segmentation is a file for dino. But in README.md, you mentioned the backbone is deit. I wondered if there is something i misunderstand.

**Comment by clxia12** [comment]
Thank you for the reminder. The link for [DeiT-T](https://pan.baidu.com/s/1684XaK4dRb8crxb8DRrQ7Q?pwd=fxqa) has been updated. Feel free to use it.
