### ISSUE TITLE
ViT-CoMer for classification task

### ISSUE THREAD

**Issue by JihwanEom** [Traffic-X/ViT-CoMer#9]
@clxia12 Hello, how did you used the multiscale features for classification task? Current backbone returns list of tensors with multiple shapes. Thanks in advance!!

```bash
        # Final Norm
        f1 = self.norm1(c1)
        f2 = self.norm2(c2)
        f3 = self.norm3(c3)
        f4 = self.norm4(c4)
        return [f1, f2, f3, f4]
```

_Originally posted by @JihwanEom in https://github.com/Traffic-X/ViT-CoMer/issues/3#issuecomment-2041005351_

**Comment by clxia12** [comment]
We use the last layer of features from the ViT branch to predict classification tasks.

**Comment by JihwanEom** [comment]
@clxia12 Thanks for reply! Then didn't you used f1, f2, f3 features? Can I understand another configuration is same with segmentation or detection tasks?

**Comment by clxia12** [comment]
Yes, we didn't use f1, f2, and f3 features and followed the ViT classification configuration.

**Comment by JihwanEom** [comment]
Thanks for your comment!
